
import '../models/quotation_input.dart';
import '../models/calculator_fields.dart';

QuotationInput initialCalculatorInput() {
  return QuotationInput(
    plantCapacity: '',
    solarPanel: CapacityBasedComponent(
      capacity: '',
      basePrice: '',
      quantity: '',
      gstRate: '5',
      unit: 'Wp',
    ),
    invertor: CapacityBasedComponent(
      capacity: '',
      basePrice: '',
      quantity: '1',
      gstRate: '5',
      unit: 'Wp',
    ),
    mountingStructure: CapacityBasedComponent(
      capacity: '',
      basePrice: '',
      quantity: '1',
      gstRate: '18',
      unit: 'Wp',
    ),
    dcdb: CapacityBasedComponent(
      capacity: '',
      basePrice: '',
      quantity: '1',
      gstRate: '18',
      unit: 'Nos',
    ),
    acdb: CapacityBasedComponent(
      capacity: '',
      basePrice: '',
      quantity: '1',
      gstRate: '18',
      unit: 'Nos',
    ),
    acArmouredCable: CapacityBasedComponent(
      capacity: '04 Sq 02C Cu',
      basePrice: '',
      quantity: '',
      gstRate: '18',
      unit: 'Mtr',
    ),
    acFlexibleCable: CapacityBasedComponent(
      capacity: '04 Sq 02C Cu',
      basePrice: '',
      quantity: '',
      gstRate: '18',
      unit: 'Mtr',
    ),
    dcCable: CapacityBasedComponent(
      capacity: '4 Sq',
      basePrice: '',
      quantity: '',
      gstRate: '18',
      unit: 'Mtr',
    ),
    acEarthingCable: CapacityBasedComponent(
      capacity: '16 Al',
      basePrice: '',
      quantity: '',
      gstRate: '18',
      unit: 'Mtr',
    ),
    earthingMaterial: CapacityBasedComponent(
      capacity: '',
      basePrice: '',
      quantity: '3',
      gstRate: '18',
      unit: 'Nos',
    ),
    la: CapacityBasedComponent(
      capacity: '',
      basePrice: '',
      quantity: '1',
      gstRate: '18',
      unit: 'Nos',
    ),
    installation: CapacityBasedComponent(
      capacity: '',
      basePrice: '',
      quantity: '1',
      gstRate: '18',
      unit: 'Wp',
    ),
    civilWork: CapacityBasedComponent(
      capacity: '',
      basePrice: '',
      quantity: '6',
      gstRate: '18',
      unit: 'Nos',
    ),
    electricalsPlumbing: CapacityBasedComponent(
      capacity: '',
      basePrice: '',
      quantity: '1',
      gstRate: '18',
      unit: 'Nos',
    ),
    transport: CapacityBasedComponent(
      capacity: '',
      basePrice: '',
      quantity: '1',
      gstRate: '18',
      unit: 'Nos',
    ),
    netMetersAndFees: CapacityBasedComponent(
      capacity: '',
      basePrice: '',
      quantity: '1',
      gstRate: '18',
      unit: 'Nos',
    ),
    netMeteringPayments: CapacityBasedComponent(
      capacity: '',
      basePrice: '',
      quantity: '1',
      gstRate: '18',
      unit: 'Nos',
    ),
    contingency: PercentageBasedComponent(percentage: '0'),
    cp1: PercentageBasedComponent(percentage: '12.50'),
    cp2: PercentageBasedComponent(percentage: '0'),
    amc: PercentageBasedComponent(percentage: '0'),
    subsidyProcessingFee: FixedAmountComponent(amount: '99'),
    isSubsidyProject: false,
  );
}
